services:
  backend:
    restart: always
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/dig-cert-nitrr/backend
    command: bash -c "python manage.py migrate &&
                      pip install -r requirements.txt &&
                      python manage.py runserver 0.0.0.0:8000"

  frontend:
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/dig-cert-nitrr/frontend"
      - "/dig-cert-nitrr/frontend/node_modules"
    command: > 
      bash -c "cp -rfu /dig-cert-nitrr/cache/node_modules/. /dig-cert-nitrr/frontend/node_modules/  
      && npm start"
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres