services:
  backend:
    image: piyushthedock/dig-cert-nitrr-backend:latest
    restart: always
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: bash -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_NAME=digcert
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - SECRET_KEY=django-secret

    depends_on:
      - db

  frontend:
    image: piyushthedock/dig-cert-nitrr-frontend:latest
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/frontend"
      - "/frontend/node_modules"
    command: npm start
    depends_on:
      - backend
    environment:
      - WATCHPACK_POLLING=true

  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=digcert
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:latest

  celery_worker:
    image: piyushthedock/dig-cert-nitrr-celery_worker
    build: ./backend
    depends_on:
      - redis
      - backend
    volumes:
      - "./backend:/backend"
    environment:
      - C_FORCE_ROOT=true
      - CELERY_BROKER=redis://redis:6379/0
    command: python -m celery -A main.tasks worker --loglevel=DEBUG

  nginx:
    image: piyushthedock/dig-cert-nitrr-nginx
    build: ./nginx
    ports:
      - "8080:80"
